### ISSUE TITLE
Выкатывание новой версии нюгета через CI

### ISSUE THREAD

**Issue by FrediKats** [kysect/BotFramework#16]
Было бы неплохо реализовать возможность выкатывать новые версии нюгета автоматически при мердже в мастер. Нужно посмотреть есть ли готовые скриптны в Github action ИЛИ если он не умеет в такое - заюзать azure devops.

**Comment by Bibletoon** [comment]
@s4xack Ну как там с CI вопрос обстоит?

**Comment by riiji** [comment]
https://github.com/kysect/BotFramework/pull/43
